### ISSUE TITLE
Rebase WIP branches onto 5.10?

### ISSUE THREAD

**Issue by Wesley-Chan** [JamiKettunen/linux-mainline-oneplus5#1]
Hi. Thank you for your good work!

I've noticed that some WIP branches are based on older versions therefore 5.10 doesn't enable all features that are ever worked. Do you have plans for this or do you need help? What does the TODO list look like in the near future?

**Comment by JamiKettunen** [comment]
Help with anything would be appreciated if you have the skill and time ;) From what I can tell the audio subsystems have missing DTS bindings (maybe more too?) for MSM8998 so [WIP-tfa9891-audio](https://github.com/JamiKettunen/linux-mainline-oneplus5/tree/WIP-tfa9891-audio) won't be worked on for a while until it's actually possible to test things.

GPU on [WIP-adreno-540-gpu](https://github.com/JamiKettunen/linux-mainline-oneplus5/tree/WIP-adreno-540-gpu) on the other hand doesn't get past early init due to clock issues, but [SoMainline people](https://github.com/SoMainline/linux/commits/angelo/somainline-msm8998-bringup) are working on that currently. It's some complicated HW though so it may take a bit before it's properly enabled :)

While DSI displays work (5T one currently untested), they are **insanely slow** in my testing even compared to simplefb which makes me want to enable them on the main branch later at the same time as the A540 GPU is usable, and there's also some issues with the used MSM8998 subsystems. SoMainline once again has some patches for those and I'm looking to integrate them with [WIP-s6e3fa5-s6e3fc1-panels](https://github.com/JamiKettunen/linux-mainline-oneplus5/tree/WIP-s6e3fa5-s6e3fc1-panels) later today after a rebase.

I also have no TODO list really myself and just work on whatever I feel like when I have time. There's still a bunch of things that don't work yet or have complicated setup (such as WLAN). I guess one thing that I'd like to do soon as well is to integrate more of the stuff into [pmaports](https://gitlab.com/postmarketOS/pmaports) so mainline setup becomes easier for users wanting to test things out :)

**Comment by Wesley-Chan** [comment]
Thank you for your quick reply! Very interesting stuff.

I'll see what I can do when I find the time.
